[package]
name = "spc"
version = "0.1.1"
authors = ["ferris <jake@fusetools.com>"]
description = "A library for manipulating SPC (Super Nintendo music) files."
homepage = "https://github.com/emu-rs/spc"
repository = "https://github.com/emu-rs/spc"
keywords = ["spc", "snes", "super", "nintendo", "music"]
license = "BSD-2-Clause"

[dependencies]
encoding_rs = "0.8.33"
